### ISSUE TITLE
Q2-5.png: n_per_row argument change

### ISSUE THREAD

**Issue by iboraham** [lz381/FoD_CA1_unit_tests#8]
Hey, 

I am seeing that [Q2-5.png](https://github.com/lz381/FoD_CA1_unit_tests/blob/main/q2-5.png)'s n_per_row argument is 3, however, it is clearly stated in question 2.5 that should be the default value which is 5:

> The function should also plot the intermediate steps using the previously defined function `plot_list`, using a default of 5 grids per row.

**Comment by lz381** [comment]
Good catch, thanks Onur! The graphic for this question might not be accurate anyway after issue #6 was clarified by Fabrizio - will update when I get the time

**Comment by lz381** [comment]
Just took a deeper look at this. I think your screen is cutting off the rest of the graphic, as the file is quite big - it'll show up if you scroll right :)
